luralab/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prov/', include('prov.urls')),
    path('', RedirectView.as_view(url='/prov/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

prov/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),

    path('emodel', views.EmodelListView.as_view(), name='emodel'),
    path('emodel/<int:pk>', views.EmodelDetailView.as_view(), name='emodel-detail'),

    path('vlan/<int:pk>', views.VlanDetailView.as_view(), name='vlan-detail')
]

urlpatterns += [
    path('equipment', views.EquipmentListView.as_view(), name='equipment'),
    path('equipment/<slug:slug>,<int:pk>', views.EquipmentDetailView.as_view(), name='equipment-detail'),

    path('equipment/create/', views.EquipmentCreate.as_view(), name='equipment_create'),
    path('equipment/<slug:slug>,<int:pk>/update/', views.EquipmentUpdate.as_view(), name='equipment_update'),
    path('equipment/<slug:slug>,<int:pk>/delete/', views.EquipmentDelete.as_view(), name='equipment_delete'),
]

urlpatterns += [
    path('vrf', views.VrfListView.as_view(), name='vrf'),
    path('vrf/<int:pk>', views.VrfDetailView.as_view(), name='vrf-detail'),

    path('vrf/create/', views.VrfCreate.as_view(), name='vrf_create'),
    path('vrf/<int:pk>/update/', views.VrfUpdate.as_view(), name='vrf_update'),
    path('vrf/<int:pk>/delete/', views.VrfDelete.as_view(), name='vrf_delete'),
]

urlpatterns += [
    path('vlan/create/', views.VlanCreate.as_view(), name='vlan_create'),
    path('vlan/<int:pk>/update/', views.VlanUpdate.as_view(), name='vlan_update'),
    path('vlan/<int:pk>/delete/', views.VlanDelete.as_view(), name='vlan_delete'),
]

prov/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Equipment(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the equipment")
    playbook = models.ForeignKey('Playbook', on_delete=models.SET_NULL, null=True)
    inventory = models.ForeignKey('Inventory', on_delete=models.SET_NULL, null=True)
    os = models.ForeignKey('Os', on_delete=models.SET_NULL, null=True)
    equip_model = models.ForeignKey('Emodel', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('equipment-detail', kwargs={'slug': self.name, 'pk':str(self.id)})


    class Meta:
        ordering = ['name']

class Vrf(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the vrf")

    equipment = models.ForeignKey('Equipment', on_delete=models.CASCADE, null=True, help_text="Equip VRF is connected to")

    loopback = models.CharField(max_length=200, help_text="Enter loopback addr, eg 1.1.1.1/32")
    linknet = models.CharField(max_length=200, help_text="Enter linknet addr, eg 1.1.1.1/31")


    def __str__(self):
        return self.name + " - " + self.loopback

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('vrf-detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']

class Vlan(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the VLAN")
    vlan_id = models.IntegerField(help_text="Enter the VLAN ID")
    network_addr = models.CharField(max_length=200, help_text="Enter net_addr in / notation. Eg. 1.1.1.0/24 ")

    vrf = models.ForeignKey('Vrf', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('vlan-detail', args=[str(self.id)])

    class Meta:
        ordering = ['name']


class Emodel(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the model")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('emodel-detail', args=[str(self.id)])


class Os(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the Operating System")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('os-detail', args=[str(self.id)])


class Inventory(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the Inventory")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('inventory-detail', args=[str(self.id)])



class Playbook(models.Model):
    name = models.CharField(max_length=200, help_text="Enter name of the Playbook")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('playbook-detail', args=[str(self.id)])

prov/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

from .models import Equipment, Emodel, Os, Vrf, Vlan
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


def index(request):
    num_equip = Equipment.objects.all().count()
    num_emodel = Emodel.objects.all().count()
    num_os = Os.objects.all().count()

    return render(
        request,
        'index.html',
        context={'num_equip':num_equip, 'num_emodel':num_emodel, 'num_os':num_os}
    )


class EquipmentListView(generic.ListView):
    model = Equipment
    paginate_by = 10


class EquipmentDetailView(generic.DetailView):
    model = Equipment


class EquipmentCreate(CreateView):
    model = Equipment
    fields = '__all__'
    initial={'name':'ny-',}


class EquipmentUpdate(UpdateView):
    model = Equipment
    fields = ['name','playbook','inventory','os','equip_model']


class EquipmentDelete(DeleteView):
    model = Equipment
    success_url = reverse_lazy('equipment')

class VrfListView(generic.ListView):
    model = Vrf
    paginate_by = 10


class VrfDetailView(generic.DetailView):
    model = Vrf


class VrfCreate(CreateView):
    model = Vrf
    fields = '__all__'
    initial={'loopback':'/32','linknet':'/31'}


class VrfUpdate(UpdateView):
    model = Vrf
    fields = ['name','equipment','loopback','linknet']


class VrfDelete(DeleteView):
    model = Vrf
    success_url = reverse_lazy('vrf')


class VlanDetailView(generic.DetailView):
    model = Vlan


class VlanCreate(CreateView):
    model = Vlan
    fields = '__all__'


class VlanUpdate(UpdateView):
    model = Vlan
    fields = ['name','vlan_id','network_addr','vrf']
    success_url = reverse_lazy('vrf')


class VlanDelete(DeleteView):
    model = Vlan
    success_url = reverse_lazy('vrf')


class EmodelListView(generic.ListView):
    model = Emodel
    paginate_by = 10


class EmodelDetailView(generic.DetailView):
    model = Emodel

prov/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Lura Lab - Utstyrsprovisjonering</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Hjem</a></li>
          <li><a href="{% url 'equipment' %}">Alt utstyr</a></li>
          <li><a href="{% url 'emodel' %}">Alle modeller</a></li>
          <li><a href="{% url 'vrf' %}">Alle VRF</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}


      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
      {% endblock %}


      </div>
    </div>

  </div>
</body>
</html>

prov/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Lura Lab Utstyrsprovisjonering</h1>

  <p>Velkommen til <em>Lura Lab Utstyrsprovisjonering</em>, en super lett website utviklet fra et <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django">eksempel</a> hos Mozillas utviklingsnettverk.

<h2>Dynamisk innhold</h2>

  <p>Luralab har følgende innhold: </p>
  <ul>
    <li><strong>Utstyr:</strong> {{ num_equip }}</li>
    <li><strong>Modeller:</strong> {{ num_emodel }}</li>
    <li><strong>Os:</strong> {{ num_os }}</li>
  </ul>

{% endblock %}

prov/templates/prov/emodel_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ emodel.name }}</h1>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Er brukt på følgende utstyr:</h4>
      <div style="margin-left:20px;margin-top:5px">
        <lu>
        {% for equipment in emodel.equipment_set.all %}
            <li><a href="{{ equipment.get_absolute_url  }}"> {{ equipment.name }}</a></li>
        {% endfor %}
        </lu>
      </div>
  </div>
{% endblock %}

prov/templates/prov/emodel_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Modeller</h1>

    {% if emodel_list %}

    <ul>

      {% for emodel in emodel_list %}
      <li>
        <a href="{{ emodel.get_absolute_url }}">{{ emodel.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no emodel in the database.</p>
    {% endif %}
{% endblock %}

prov/templates/prov/equipment_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Equipment</h1>

<p>Are you sure you want to delete the equipment: {{ equipment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

prov/templates/prov/equipment_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ equipment.name }}</h1>
  <a href="{{ equipment.get_absolute_url }}/update">Endre {{ equipment.name }}</a>
    <br/>
    <br/>
  <ul>
      <li><strong>Playbook:</strong> {{ equipment.playbook }}</li>
      <li><strong>OS:</strong> {{ equipment.os }}</li>
      <li><strong>Inventory:</strong> {{ equipment.inventory }}</li>
      <li><strong>Model:</strong> <a href="{{ equipment.equip_model.get_absolute_url }}"> {{ equipment.equip_model }}</a></li>
  </ul>

    <h2>VRF</h2>
    <a href="{% url 'vrf_create' %}">Nytt VRF</a>
    <br />
    <br />
    {% if equipment.vrf_set.all  %}
    <table class="table">

        {% for vrf in equipment.vrf_set.all %}
            <tr>
                <td>
                    <a href="{{ vrf.get_absolute_url }}">{{ vrf.name }}</a>
                    <a href="{{ vrf.get_absolute_url }}/update"> - (Endre)</a>

                </td>
                <td>{{ vrf.loopback }}</td>
                <td>{{ vrf.linknet }}</td>
                <td>

                    <ul>
                        {% for vlan in vrf.vlan_set.all %}
                            <li>VLAN{{ vlan.vlan_id }} - {{ vlan.network_addr }}</li>
                        {% endfor %}
                    </ul>

                </td>
            </tr>
        {% endfor %}

    </table>

    {% else %}
    <p>Utstyr mangler VRF</p>
    {% endif %}
{% endblock %}

prov/templates/prov/equipment_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

prov/templates/prov/equipment_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Utstyr</h1>

    {% if equipment_list %}

        <table class="table">
          {% for equipment in equipment_list %}
          <tr>
            <td>
               <a href="{{ equipment.get_absolute_url }}">{{ equipment.name }}</a>
            </td>
          <td>
              {{ equipment.os }}
          </td>
          <td>
             {{equipment.equip_model}}
          </td>
          <td>
          <ul>
           {% for vrf in equipment.vrf_set.all %}
              <li> <a href="{{ vrf.get_absolute_url }}">{{ vrf.name }} ({{ vrf.loopback }})</a></li>
           {% endfor %}
          </ul>
          </td>
          </tr>
          {% endfor %}
        </table>
    {% else %}
      <p>There are no equipment in the database.</p>
    {% endif %}
{% endblock %}

prov/templates/prov/vlan_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete VLAN</h1>

<p>Are you sure you want to delete the VLAN: {{ vlan }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

prov/templates/prov/vlan_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>VLAN - {{ vlan.name }}</h1>

  <div style="margin-left:20px;margin-top:20px">
<table class="table">
    <tr>
       <td>VLAN{{ vlan.vrf_id }}</td>
        <td>{{ vlan.network_addr }}</td>
    </tr>
</table>
  </div>
{% endblock %}

prov/templates/prov/vlan_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

prov/templates/prov/vrf_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete VRF</h1>

<p>Are you sure you want to delete the VRF: {{ vrf }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

prov/templates/prov/vrf_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ vrf.name }}</h1>

  <p><strong>Equipment:</strong> <a href="{{ vrf.equipment.get_absolute_url }}">{{ vrf.equipment }}</a> </p>
  <p><strong>Loopback:</strong> {{ vrf.loopback }}</p>
  <p><strong>Linknet:</strong> {{ vrf.linknet }}</p>

  <h2>VLANS:</h2>
    <a href="{% url 'vlan_create' %}">Nytt VLAN</a>
    {% if vrf.vlan_set.all %}
     <table class="table">
         {% for vlan in vrf.vlan_set.all %}
        <tr>
            <td>{{ vlan.name }} -
                <a href="{{ vlan.get_absolute_url }}/update">Endre</a> -
                <a href="{{ vlan.get_absolute_url }}/delete">Slett</a>
            </td>
            <td>VLAN{{ vlan.vlan_id }}</td>
            <td>{{ vlan.network_addr }}</td>
        </tr>

         {% endfor %}

    </table>
    {% else %}
        <p> Ingen VLAN er definert </p>
    {% endif %}
{% endblock %}

prov/templates/prov/vrf_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

prov/templates/prov/vrf_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Vrf</h1>

    {% if vrf_list %}

    <ul>

      {% for vrf in vrf_list %}
      <li>
        <a href="{{ vrf.get_absolute_url }}">{{ vrf.name }} ({{ vrf.equipment }})</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no vrf in the database.</p>
    {% endif %}
{% endblock %}